# Generated by Django 5.1.5 on 2025-01-24 17:16
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_merge_0004_trigram_ext_0005_trigram_ext'),
    ]

    operations = [
        TrigramExtension()
    ]
